ALTER TABLE mascotas ADD COLUMN alimento_especial BOOLEAN DEFAULT FALSE;
ALTER TABLE mascotas ADD COLUMN horario_preferido VARCHAR(100) DEFAULT NULL;
ALTER TABLE mascotas ADD COLUMN camita BOOLEAN DEFAULT FALSE;
ALTER TABLE mascotas ADD COLUMN mantita BOOLEAN DEFAULT FALSE;

SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'zen_spa' AND TABLE_NAME = 'mascotas'
ORDER BY ORDINAL_POSITION;
